Progressbar: lib/statusbar.c File Reference
statusbar.c File Reference
#include "statusbar.h"
Functions
statusbar * statusbar_new_with_format (const char *label, const char *format)
Create a new statusbar with the specified label and format string.
statusbar * statusbar_new (const char *label)
Create a new statusbar with the specified label.
void statusbar_free (statusbar *bar)
Free an existing progress bar. Don't call this directly; call statusbar_finish instead.
void statusbar_inc (statusbar *bar)
Increment the given statusbar.
void statusbar_draw (statusbar *bar)
void statusbar_finish (statusbar *bar)
Finalize (and free!) a statusbar. Call this when you're done.
Function Documentation
void statusbar_draw (statusbar * bar)
Draw a statusbar to the screen. Don't call this directly, as it's called internally by statusbar_inc.
References _statusbar_t::format, _statusbar_t::format_index, _statusbar_t::label, and _statusbar_t::last_printed.
Referenced by statusbar_inc().
void statusbar_finish (statusbar * bar)
Finalize (and free!) a statusbar. Call this when you're done.
References _statusbar_t::label, _statusbar_t::last_printed, _statusbar_t::start_time, and statusbar_free().
void statusbar_free (statusbar * bar)
Free an existing progress bar. Don't call this directly; call statusbar_finish instead.
References _statusbar_t::format.
Referenced by statusbar_finish().
void statusbar_inc (statusbar * bar)
Increment the given statusbar.
References _statusbar_t::format_index, _statusbar_t::format_length, and statusbar_draw().
statusbar* statusbar_new (const char * label)
Create a new statusbar with the specified label.
References statusbar_new_with_format().
statusbar* statusbar_new_with_format (const char * label, const char * format)
Create a new statusbar with the specified label and format string.
Referenced by statusbar_new().